# Example security rules for Palo Alto Networks SCM
# This file can be applied with the CLI command:
# poetry run python -m src.scm_cicd.cli apply config/security-rules/example.yaml

# Allow internal to internet web traffic
- name: "allow-internal-web"
  folder: "Texas"
  description: "Allow internal users to access web applications"
  from_: ["DMZ"]
  to_: ["DIA"]
  source: ["internal-subnet"]
  destination: ["any"]
  application: ["web-browsing", "ssl", "dns"]
  service: ["application-default"]
  category: ["any"]
  source_user: ["any"]
  action: "allow"
  log_end: true
  tag: ["Automation", "CICD"]

# Block known malicious sites
- name: "block-malicious"
  folder: "Texas"
  description: "Block traffic to known malicious destinations"
  from_: ["DMZ"]
  to_: ["DIA"]
  source: ["internal_network4", "internal_network5"]
  destination: ["panw-highrisk-ip-list"]
  application: ["any"]
  service: ["any"]
  category: ["any"]
  source_user: ["any"]
  action: "deny"
  log_start: true
  log_end: true
  tag: ["Automation", "CICD"]
