# Example security rules for Palo Alto Networks SCM
# This file can be applied with the CLI command:
# poetry run python -m src.scm_cicd.cli apply config/security-rules/example.yaml

# Allow internal to internet web traffic
- name: "allow-internal-web"
  folder: "Global"
  description: "Allow internal users to access web applications"
  from_: ["trust"]
  to_: ["untrust"]
  source: ["internal-subnet"]
  destination: ["any"]
  application: ["web-browsing", "ssl", "dns"]
  service: ["application-default"]
  action: "allow"
  log_end: true
  tag: ["policy-type:allow", "service:web"]

# Block known malicious sites
- name: "block-malicious"
  folder: "Global"
  description: "Block traffic to known malicious destinations"
  from_: ["trust"]
  to_: ["untrust"]
  source: ["any"]
  destination: ["malicious-destinations"]
  application: ["any"]
  service: ["any"]
  action: "deny"
  log_start: true
  log_end: true
  tag: ["policy-type:block", "threat:malicious-sites"]
