# SCM-compatible security rules that only use existing resources
# This file contains both new rules and modifications to existing rules

# This is an existing rule that should be updated (only using existing tags)
- name: "allow-internal-web"
  folder: "Texas"
  description: "Updated: Allow internal users to access web applications with additional protocols"
  from_: ["DMZ"]
  to_: ["DIA"]
  source: ["internal_network4", "internal_network5"]
  destination: ["any"]
  application: ["web-browsing", "ssl", "dns", "ssh", "ping"]
  service: ["application-default"]
  category: ["any"]
  source_user: ["any"]
  action: "allow"
  log_end: true
  tag: ["Automation", "CICD"]  # Only using existing tags

# This is a new rule that should be created (only using existing tags)
- name: "allow-monitoring-traffic"
  folder: "Texas"
  description: "Allow monitoring systems to access all devices for telemetry"
  from_: ["DMZ"]
  to_: ["DIA"]
  source: ["internal_network4"]
  destination: ["any"]
  application: ["ping", "ssh", "snmp"]
  service: ["application-default"]
  category: ["any"]
  source_user: ["any"]
  action: "allow"
  log_end: true
  tag: ["Automation", "CICD"]  # Only using existing tags
