name: SCM Security Rules Management

on:
  push:
    branches: [ main ]
    paths:
      - 'config/security-rules/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'config/security-rules/**'
  workflow_dispatch:
    # Removed inputs to resolve CKV_GHA_7 finding
    # Using environment configuration in the jobs instead

# Set restricted permissions as a security best practice (addressing CKV2_GHA_1)
permissions:
  contents: read

jobs:
  security-scan:
    name: Security and Secrets Scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Explicitly set job permissions
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for some security scanners that need git history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Scan for secrets with Checkov
        run: |
          checkov --directory . --framework secrets

      - name: Scan for secrets with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate:
    name: Validate Security Rules
    runs-on: ubuntu-latest
    needs: security-scan
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Run security checks with Checkov
        run: |
          checkov -d config/security-rules --framework yaml

      - name: Validate rule syntax
        run: |
          # Validate all rule files in the config directory
          for file in config/security-rules/*.yaml; do
            echo "Validating $file"
            python -m scm_cicd.cli apply "$file" --dry-run
          done

  deploy:
    name: Deploy Security Rules
    needs: validate
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    # Using environment configuration instead of inputs
    environment: production
    permissions:
      contents: read  # Only read permission needed for deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Setup SCM credentials
        run: |
          # Create .secrets.yaml from environment variables
          cat > .secrets.yaml << EOL
          default:
            client_id: "${PAN_CLIENT_ID}"
            client_secret: "${PAN_CLIENT_SECRET}"
            tsg_id: "${PAN_TSG_ID}"
            api_base_url: "https://api.strata.paloaltonetworks.com"
            token_url: "https://auth.apps.paloaltonetworks.com/am/oauth2/access_token"
            log_level: "INFO"
          EOL
        env:
          PAN_CLIENT_ID: ${{ secrets.PAN_CLIENT_ID }}
          PAN_CLIENT_SECRET: ${{ secrets.PAN_CLIENT_SECRET }}
          PAN_TSG_ID: ${{ secrets.PAN_TSG_ID }}

      - name: Apply security rules
        run: |
          # Apply all rule files in the config directory
          for file in config/security-rules/*.yaml; do
            echo "Applying rules from $file"
            python -m scm_cicd.cli apply "$file" --commit
          done
